### ISSUE TITLE
NumberFormatException when pattern contains trailing or duplicated space

### ISSUE THREAD

**Issue by centralhardware** [InsanusMokrassar/krontab#126]
```kotlin
suspend fun main() {
    doOnceTz("* * * * * * ") {

    }
}
```

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:565)
	at java.base/java.lang.Integer.parseInt(Integer.java:685)
	at dev.inmo.krontab.internal.ParserKt.createSimpleScheduler(Parser.kt:33)
	at dev.inmo.krontab.internal.ParserKt.parseYears(Parser.kt:42)
	at dev.inmo.krontab.KrontabConfig.scheduler-impl(KrontabConfig.kt:113)
	at dev.inmo.krontab.StringParserKt.createSimpleScheduler(StringParser.kt:77)
	at dev.inmo.krontab.StringParserKt.buildSchedule(StringParser.kt:87)
	at me.centralhardware.telegram.MainKt.main(Main.kt:10)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:223)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at me.centralhardware.telegram.MainKt.main(Main.kt)

```

```kotlin
suspend fun main() {
    doOnce(" * * * * * *") {

    }
}
```

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:565)
	at java.base/java.lang.Integer.parseInt(Integer.java:685)
	at dev.inmo.krontab.internal.ParserKt.createSimpleScheduler(Parser.kt:33)
	at dev.inmo.krontab.internal.ParserKt.parseSeconds(Parser.kt:47)
	at dev.inmo.krontab.KrontabConfig.scheduler-impl(KrontabConfig.kt:119)
	at dev.inmo.krontab.StringParserKt.createSimpleScheduler(StringParser.kt:77)
	at dev.inmo.krontab.StringParserKt.buildSchedule(StringParser.kt:87)
	at me.centralhardware.telegram.MainKt.main(Main.kt:11)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:223)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at me.centralhardware.telegram.MainKt.main(Main.kt)

```

```kotlin
suspend fun main() {
    doOnce("*  * * * * *") {

    }
}
```

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:565)
	at java.base/java.lang.Integer.parseInt(Integer.java:685)
	at dev.inmo.krontab.internal.ParserKt.createSimpleScheduler(Parser.kt:33)
	at dev.inmo.krontab.internal.ParserKt.parseMinutes(Parser.kt:46)
	at dev.inmo.krontab.KrontabConfig.scheduler-impl(KrontabConfig.kt:120)
	at dev.inmo.krontab.StringParserKt.createSimpleScheduler(StringParser.kt:77)
	at dev.inmo.krontab.StringParserKt.buildSchedule(StringParser.kt:87)
	at me.centralhardware.telegram.MainKt.main(Main.kt:10)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:223)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at me.centralhardware.telegram.MainKt.main(Main.kt)

```

```kotlin
suspend fun main() {
    doOnce("sdf * * * * *") {

    }
}
```

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "sd0"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:588)
	at java.base/java.lang.Integer.parseInt(Integer.java:685)
	at dev.inmo.krontab.internal.ParserKt.createSimpleScheduler(Parser.kt:33)
	at dev.inmo.krontab.internal.ParserKt.parseSeconds(Parser.kt:47)
	at dev.inmo.krontab.KrontabConfig.scheduler-impl(KrontabConfig.kt:119)
	at dev.inmo.krontab.StringParserKt.createSimpleScheduler(StringParser.kt:77)
	at dev.inmo.krontab.StringParserKt.buildSchedule(StringParser.kt:87)
	at me.centralhardware.telegram.MainKt.main(Main.kt:10)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:223)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at me.centralhardware.telegram.MainKt.main(Main.kt)

Process finished with exit code 1

```

```kotlin
suspend fun main() {
    doOnce("* * * * * * oo") {
        println("sdf")
    }
}
```

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "oo"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:588)
	at java.base/java.lang.Integer.parseInt(Integer.java:685)
	at dev.inmo.krontab.internal.ParserKt.createSimpleScheduler(Parser.kt:33)
	at dev.inmo.krontab.internal.ParserKt.parseYears(Parser.kt:42)
	at dev.inmo.krontab.KrontabConfig.scheduler-impl(KrontabConfig.kt:113)
	at dev.inmo.krontab.StringParserKt.createSimpleScheduler(StringParser.kt:77)
	at dev.inmo.krontab.StringParserKt.buildSchedule(StringParser.kt:87)
	at me.centralhardware.telegram.MainKt.main(Main.kt:14)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:223)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at me.centralhardware.telegram.MainKt.main(Main.kt)

Process finished with exit code 1

```

**Comment by centralhardware** [comment]
```kotlin
suspend fun main() {
    doOnce("0, * * * *") {
        println("sdf")
    }
}
```

```
Exception in thread "main" java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:565)
	at java.base/java.lang.Integer.parseInt(Integer.java:685)
	at dev.inmo.krontab.internal.ParserKt.createSimpleScheduler(Parser.kt:33)
	at dev.inmo.krontab.internal.ParserKt.parseSeconds(Parser.kt:117)
	at dev.inmo.krontab.KrontabConfig.scheduler-impl(KrontabConfig.kt:130)
	at dev.inmo.krontab.StringParserKt.createSimpleScheduler(StringParser.kt:77)
	at dev.inmo.krontab.StringParserKt.buildSchedule(StringParser.kt:87)
	at me.centralhardware.telegram.MainKt.main(Main.kt:10)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:223)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at me.centralhardware.telegram.MainKt.main(Main.kt)

Process finished with exit code 1

```
