### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by centralhardware** [InsanusMokrassar/krontab#127]
```kotlin
suspend fun main() {
    doOnce("1 2 3 4") {
        println("sdf")
    }
}
```

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 4
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:365)
	at java.base/java.util.ArrayList.get(ArrayList.java:428)
	at dev.inmo.krontab.KrontabConfig.scheduler-impl(KrontabConfig.kt:97)
	at dev.inmo.krontab.StringParserKt.createSimpleScheduler(StringParser.kt:77)
	at dev.inmo.krontab.StringParserKt.buildSchedule(StringParser.kt:87)
	at me.centralhardware.telegram.MainKt.main(Main.kt:10)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at me.centralhardware.telegram.MainKt$main$3.invoke(Main.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:223)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at me.centralhardware.telegram.MainKt.main(Main.kt)

```

**Comment by InsanusMokrassar** [comment]
It is supposed, that you will pass at least 5 parts of krontab :)
